# -*- coding: utf-8 -*-
"""Grog APi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reV4Hn6IENYdPn06MuF9bPtwRZLsoqJi
"""

!pip install requests

import requests

#  Groq API key
API_KEY = "My APi kEy"

#  Groq API endpoint for model inference
API_URL = "https://api.groq.com/openai/v1/chat/completions"

# request headers
headers = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json"
}

# request data using a chat model
data = {
    "model": "llama3-70b-8192",
    "messages": [
        {"role": "system", "content": "You are a helpful assistant that translates English to Finnish."},
        {"role": "user", "content": "Translate this to Finnish: Hello!! how are you?"}
    ],
    "temperature": 0.7
}


response = requests.post(API_URL, json=data, headers=headers)

# Check and display responsec
if response.status_code == 200:
    translation = response.json()["choices"][0]["message"]["content"]
    print("Translation:", translation)
else:
    print("Error:", response.status_code, response.text)